'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const localeRoot = path.join(root, 'web', 'locales');
const locales = ['en', 'fr', 'pt-BR', 'pt-PT', 'es', 'ru', 'pl', 'de', 'tr', 'fi', 'it', 'sv', 'zh-CN', 'da'];
const catalogues = {};
for (const locale of locales) {
  const file = path.join(localeRoot, locale, 'common.json');
  catalogues[locale] = JSON.parse(fs.readFileSync(file, 'utf8'));
}
fs.writeFileSync(path.join(root, 'web', 'locales.js'),
  '/* Generated by npm run i18n:compile. */\nwindow.REALM_TOOLS_LOCALES=' + JSON.stringify(catalogues) + ';\n');
console.log(`Compiled ${locales.length} locale catalogues.`);
