/*
 * Which item you are enchanting, and what that tells us.
 *
 * Two things follow from the item itself and never have to be asked:
 *   - its slot (weapon / ability / armor / ring),
 *   - the dust its rerolls are billed in, which depends on the item's tier.
 *
 * One thing does NOT follow from it: the rarity, and therefore the number of
 * enchantment slots. Rarity is rolled when the item drops (50 % / 37.5 % /
 * 25 % / 12.5 % for Uncommon / Rare / Legendary / Divine), so two copies of the
 * same item can have a different number of slots. It stays a manual choice.
 *
 * The catalogue itself lives in web/item-catalog.json and is regenerated by
 * tools/fetch-items.js from the RotMG wiki. This file holds only the rules that
 * read it: the tier bands, the name aliases and the lookup.
 */
var EnchantItems = (function () {
  'use strict';

  // Tiered gear: the dust follows the tier number, in three bands per slot.
  // Kept here as well as in the generator so a stale catalogue is still
  // interpreted consistently.
  const TIER_BANDS = {
    WEAPON:  { Green: [1, 9], Red: [10, 12], Purple: [13, 14] },
    ABILITY: { Green: [1, 4], Red: [5, 6],   Purple: [7, 7] },
    ARMOR:   { Green: [1, 9], Red: [10, 12], Purple: [13, 14] },
    RING:    { Green: [1, 4], Red: [5, 6],   Purple: [7, 7] }
  };
  const TIER_LABEL = { WEAPON: 'Weapon', ABILITY: 'Ability', ARMOR: 'Armor', RING: 'Ring' };

  /*
   * Corrections applied on top of the scraped catalogue, each with its reason.
   * The wiki's reroll tables predate the Advance of Oryx set, so its dust is
   * missing there even though the item is listed on the ring index.
   */
  const OVERRIDES = {
    // Empty on purpose: every correction that used to live here is now
    // covered by tools/item-dust.txt, which reads each item's own page —
    // including the Nightmatter Circlet, whose page confirms Red dust. The
    // hook stays so a future discrepancy can be fixed without regenerating.
  };

  // The Qt awakened-items file and the wiki spell a few names differently.
  const ALIASES = {
    "pirate king's cutlass": 'Pirate King Cutlass',
    'doku no ken': 'Doku No Ken'
  };

  const normalise = name => String(name || '').trim().toLowerCase().replace(/\s+/g, ' ');

  function dustForTier(type, tier) {
    const bands = TIER_BANDS[type];
    if (!bands || tier === undefined || tier === null) return null;
    for (const [dust, [low, high]] of Object.entries(bands)) if (tier >= low && tier <= high) return dust;
    return null;
  }

  let index = new Map();
  let byNormalised = new Map();

  /*
   * Builds the lookup from a catalogue produced by tools/fetch-items.js.
   * Entries are compact on disk ({s: slot, d: dust, t: tier, f: sprite}); they
   * are expanded here into what the interface reads.
   */
  function load(catalog) {
    index = new Map();
    byNormalised = new Map();
    const items = (catalog && catalog.items) || {};

    for (const [name, raw] of Object.entries(items)) {
      const override = OVERRIDES[name] || {};
      const entry = {
        name,
        type: raw.s || null,
        dust: override.dust || raw.d || dustForTier(raw.s, raw.t) || null,
        tier: raw.t === undefined ? null : raw.t,
        tiered: raw.t !== undefined,
        sprite: raw.f || null,
        note: override.note || ''
      };
      index.set(name, entry);
    }

    // Synthetic entries so a plain tiered item can be picked by tier alone,
    // for anyone who does not remember the exact name.
    for (const [type, bands] of Object.entries(TIER_BANDS)) {
      const max = Math.max(...Object.values(bands).map(range => range[1]));
      for (let tier = 1; tier <= max; tier++) {
        const dust = dustForTier(type, tier);
        const name = `Tier ${tier} ${TIER_LABEL[type]}`;
        if (dust && !index.has(name)) index.set(name, { name, type, dust, tier, tiered: true, sprite: null, note: '' });
      }
    }

    for (const [name, entry] of index) byNormalised.set(normalise(name), entry);
    return index;
  }

  // Tolerant lookup: exact name, then case/spacing-insensitive, then an alias.
  function lookup(name) {
    if (!name) return null;
    if (index.has(name)) return index.get(name);
    const key = normalise(name);
    if (byNormalised.has(key)) return byNormalised.get(key);
    const alias = ALIASES[key];
    return alias ? index.get(alias) || null : null;
  }

  return {
    TIER_BANDS, TIER_LABEL, ALIASES, OVERRIDES,
    dustForTier, normalise, load, lookup,
    get index() { return index; },
    get size() { return index.size; }
  };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = EnchantItems;
